"""empty message

Revision ID: 0a5cdf08f7b8
Revises: 7935ca28cd3e
Create Date: 2025-03-22 12:54:28.875075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5cdf08f7b8'
down_revision = '7935ca28cd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_request', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_of_completion', sa.DateTime(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.drop_column('date_of_completion')
        batch_op.drop_column('date_of_request')

    # ### end Alembic commands ###
