"""empty message

Revision ID: 2d484971bd96
Revises: f2b1c92599cd
Create Date: 2025-02-28 11:59:39.802461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d484971bd96'
down_revision = 'f2b1c92599cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
