"""empty message

Revision ID: 71e0c507e01f
Revises: d7a42a374a44
Create Date: 2025-03-22 11:07:14.258008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e0c507e01f'
down_revision = 'd7a42a374a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('u_id', sa.INTEGER(), nullable=False),
    sa.Column('e_id', sa.INTEGER(), nullable=False),
    sa.Column('s_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=80), nullable=False),
    sa.ForeignKeyConstraint(['e_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['s_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['u_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
