"""empty message

Revision ID: 780ae14464c0
Revises: 3156cc6dac80
Create Date: 2025-03-22 17:08:51.896098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780ae14464c0'
down_revision = '3156cc6dac80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('e_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_rating_employee', 'employee', ['e_id'], ['employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rating_employee', type_='foreignkey')
        batch_op.drop_column('e_id')

    # ### end Alembic commands ###
